apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: uyahya
spec:
  type: LoadBalancer
  selector:
    app: application-container
  ports:
  - port: 30000
    targetPort: 8081